# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: run coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test:prod

    - name: Coverage Comment
      uses: ewjoachim/coverage-comment-action@v1.0.3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        COVERAGE_FILE: 'coverage/netflow/cobertura-coverage.xml'
        MINIMUM_GREEN: 90
        MINIMUM_ORANGE: 70

    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3.0
      with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: 'coverage/netflow/cobertura-coverage.xml'
