name: build frontend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: rg.fr-par.scw.cloud/funcscwnetflowldnox33w
      NAME: netflow
      BRANCH: frontend
    name: Deploy on Scaleway Containers
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: nologin
          password: ${{ secrets.SECRET_KEY }}

      - name: Build
        uses: docker/build-push-action@v3.0.0
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ env.NAME }}:${{ env.BRANCH }}
        with:
          file: Dockerfile.front
          push: true
          tags: ${{ env.IMAGE }}
          build-args: SYNCFUSION_LICENSE=${{ secrets.SYNCFUSION_LICENSE }}

      - name: Scaleway Container Deploy action
        id: deploy
        uses:  philibea/scaleway-containers-deploy@v1.0.7
        with:
          type: deploy
          scw_access_key:  ${{ secrets.ACCESS_KEY }}
          scw_secret_key: ${{ secrets.SECRET_KEY }}
          scw_containers_namespace_id: ${{ secrets.CONTAINERS_NAMESPACE_ID }}
          scw_registry: ${{ env.REGISTRY }}/${{ env.NAME }}:${{ env.BRANCH }}
          scw_memory_limit: 256
